---
name: Lidarr
version: pr-plugins
slug: lidarr
description: Looks and smells like Sonarr but made for music
startup: application
boot: auto
ingress: true
ingress_port: 8686
ingress_entry: "/"
url: https://github.com/gr1los/ha-addons/lidarr
image: ghcr.io/hotio/lidarr
logo: https://raw.githubusercontent.com/gr1los/addon-lidarr/main/lidarr/logo.png
maintainers:
  - gr1los
environment:
  PUID: "1000"
  PGID: "1000"
webui: http://[HOST]:[PORT:8686]
init: false
arch:
  - amd64
map:
  - type: media
    read_only: False
  - type: addon_config
    read_only: False
  - type: share
    read_only: False
ports:
  8686/tcp: 8686
